# Generated by Django 5.1.5 on 2025-02-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_counter_views_alter_blog_flag_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='flag_publication',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
